### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by JonaVDV** [JonaVDV/sveltekit-kql#1]
A roadmap for what is to come on the journey to 1.0

- [ ] write tests.
- [ ] improved typescript support
- [ ] possibly a config file
- [ ] better ways of integrating with load functions
- [ ] other ideas?
